### PR TITLE
created "events" section

### PR DESCRIPTION
**Pull request by A-R-P-I-T-JAIN**
navigate to '/events' to  see events section

### CODE REVIEW

**Comment by atharv-av** [comment]
> navigate to '/events' to see events section

ERROR 404
image

try experimenting with the routing in the deployed page.

**Comment by atharv-av** [comment]
> > navigate to '/events' to see events section
> 
> ERROR 404 image
> 
> Try experimenting with the routing in the deployed page.
I know it would be working on your localhost. But it is not working on the live website. See if you can do the same for the "/signup" route as well.

**Comment by A-R-P-I-T-JAIN** [comment]
Ok , i will try to fix it

**Review by A-R-P-I-T-JAIN — COMMENTED** [review]
..

**Pull request closed without merging**
