### PR TITLE
Responsive "Explore by Category" section

### PR DESCRIPTION
**Pull request by AkshatSinghThakur**
This is the fully responsive category section.
Please review the code.
sir you assigned the same issue to me few days ago in a different repository.

### CODE REVIEW

**Comment by atharv-av** [comment]
> This is the fully responsive category section. Please review the code. sir you assigned the same issue to me few days ago in a different repository.

This section is glitching in your code.
image

**Comment by AkshatSinghThakur** [comment]
Sir I have not made this section, I worked on category section. 
This is Why Join Us section.
 
categpry 3
category 2
category

**Comment by atharv-av** [comment]
I know but only your code has render problems. Moreover, your PR has some conflicts which you need to resolve. 
@AkshatSinghThakur

**Comment by atharv-av** [comment]
> I know but only your code has render problems. Moreover, your PR has some conflicts which you need to resolve. @AkshatSinghThakur
The UI is perfect. I would suggest you to clone the code again and add your files. You might be using the older code.

**Comment by AkshatSinghThakur** [comment]
Ok sir I'll do it

**Pull request closed without merging**
