### PR TITLE
Add Explore By Category section

### PR DESCRIPTION
**Pull request by BhaveshDiwale**
Added fully responsive Explore By Category section.

### CODE REVIEW

**Comment by atharv-av** [comment]
> Added fully responsive Explore By Category section.

I am not able to get a deploy preview. If you have added a route, please mention it here.

**Comment by BhaveshDiwale** [comment]
> > Added fully responsive Explore By Category section.
> 
> I am not able to get a deploy preview. If you have added a route, please mention it here.

Ok I have not called the Explore category section.
I will commit 1 more time.
Thanks for mentioning

**Comment by BhaveshDiwale** [comment]
Hi! The issue is now resolved. The component is now below Meet Our Team section.
Please merge it to your code. Thanks.

**Comment by atharv-av** [comment]
> Hi! The issue is now resolved. The component is now below Meet Our Team section. Please merge it to your code. Thanks.

Thank you. Your PR has been merged.

**Pull request merged**
