### PR TITLE
Added Success Stories section with UI created using Spline Design.

### PR DESCRIPTION
**Pull request by sohamt-21**
Added success stories component in React.JS using created using Spline Design.

### CODE REVIEW

**Comment by sohamt-21** [comment]
@atharv-av  pr from initial repo to here. Review and lmk any changes required.

**Comment by sohamt-21** [comment]
> @atharv-av pr from initial repo to here. Review and lmk any changes required.

@atharv-av

**Comment by atharv-av** [comment]
The UI is fine but it is coinciding with other sections.
image

**Comment by sohamt-21** [comment]
okay wait let me check , it was not coinciding for me though , lemme check again and i'll change it.

**Comment by sohamt-21** [comment]
Screenshot 2023-10-27 at 7 53 21 PM
It's actually correct from my end though, could you please refresh and let it load and then scroll.

**Comment by atharv-av** [comment]
Alright, I have merged your PR.

**Comment by sohamt-21** [comment]
Thank You!

**Comment by sohamt-21** [comment]
If it doesnt work in the final version you can remove margin-top of container in Success.css.

**Pull request merged**
